
#
# vNSF Store environment
#

FROM centos:7

LABEL project="${CNTR_PROJECT}"

# Dependencies
RUN yum update -y && \
    yum install -y epel-release && yum makecache fast && \
    yum install -y python34 python34-pip && \
    pip3 install --upgrade pip && \
    yum clean all

WORKDIR ${CNTR_FOLDER_DEV}

ENTRYPOINT ["${CNTR_FOLDER_DEV}/docker/setup.sh"]
